### Crear un nou carrito
POST http://localhost:5000/api/carritos HTTP/1.1
Content-Type: application/json

{
  "id_carrito": "CARR001",
  "id_usuario": "68f5f6accb7cf445387aa124",
  "items": [
    {
      "id_pala": "68f60d9acb7cf445387aa16b",
      "cantidad": 2
    },
    {
      "id_pala": "68f60d9acb7cf445387aa18a",
      "cantidad": 1
    }
  ]
}

### ===============================
### Obtenir tots els carritos
GET http://localhost:5000/api/carritos HTTP/1.1
Content-Type: application/json

### ===============================
### Obtenir carrito per ID
GET http://localhost:5000/api/carritos/6909c089e27b1fe97270d526 HTTP/1.1
Content-Type: application/json

### ===============================
### Actualitzar carrito
PUT http://localhost:5000/api/carritos/6909c089e27b1fe97270d526 HTTP/1.1
Content-Type: application/json

{
  "items": [
    {
      "id_pala": "68f60d9acb7cf445387aa16b",
      "cantidad": 3
    }
  ]
}

### ===============================
### Eliminar carrito
DELETE http://localhost:5000/api/carritos/6909c089e27b1fe97270d526 HTTP/1.1
Content-Type: application/json
