### Crear nuevo pedido
POST http://localhost:5000/api/pedidos HTTP/1.1
Content-Type: application/json

{
  "id_pedido": "PED001",
  "id_usuario": "68f5f71ccb7cf445387aa12bb", 
  "id_pala": "PALA123",
  "cantidad": 2,
  "precio_unitario": 120.50,
  "fecha": "2025-10-20",
  "estado": "pendiente",
  "total": 241.00
}

### Obtener todos los pedidos
GET http://localhost:5000/api/pedidos HTTP/1.1
Content-Type: application/json

### Obtener un pedido por ID
GET http://localhost:5000/api/pedidos/6909ba46181dfac00d24f4d6 HTTP/1.1
Content-Type: application/json

### Actualizar pedido
PUT http://localhost:5000/api/pedidos/6909ba46181dfac00d24f4d6 HTTP/1.1
Content-Type: application/json

{
  "estado": "enviado"
}

### Eliminar pedido
DELETE http://localhost:5000/api/pedidos/6909ba46181dfac00d24f4d6 HTTP/1.1
Content-Type: application/json
